import type { PostCardData } from './types'

export const MOCK_POSTS: PostCardData[] = [
  {
    uuid: 'mock-1',
    author_uuid: 'user-abc-123',
    author_meta: {
      balance: 2_500_000,
      subscription_type: 1,
      role: 'user',
      elo_rating: 1850,
      gender: 'M',
      age: 28,
      arena: 'London',
    },
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    title: 'Market outlook for Q3',
    text: 'Looking at the macro trends, I think we\'re in for a volatile quarter. The Fed signals are mixed and earnings season is going to be rough.\n\nWhat\'s everyone positioning for?',
    topic: 'Stocks',
    post_type: 1,
    post_meta: { platform: 'ios' },
    upvote_count: 42,
    view_count: 1203,
    comment_count: 18,
  },
  {
    uuid: 'mock-2',
    author_uuid: 'user-def-456',
    author_meta: {
      balance: 850_000,
      subscription_type: 1,
      elo_rating: 1620,
      gender: 'F',
      age: 24,
      arena: 'Dubai',
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    text: 'Just closed my first seven-figure real estate deal. Took 18 months from first offer to closing. The patience paid off.\n\nHappy to share the playbook if anyone\'s interested.',
    topic: 'Real estate',
    post_type: 1,
    post_meta: {
      platform: 'web',
      src: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
      media_type: 'image',
    },
    upvote_count: 127,
    view_count: 5400,
    comment_count: 56,
  },
  {
    uuid: 'mock-3',
    author_uuid: 'user-ghi-789',
    author_meta: {
      balance: 12_000_000,
      subscription_type: 2,
      role: 'vip',
      elo_rating: 2100,
      gender: 'M',
      age: 35,
      arena: 'Singapore',
    },
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    title: 'Will BTC break $100k this month?',
    text: 'Technical analysis vs fundamentals — where do you stand?',
    topic: 'Cryptocurrency',
    post_type: 2,
    post_meta: {
      platform: 'android',
      poll: ['Yes, easily', 'Maybe', 'No chance', 'Already shorting'],
    },
    upvote_count: 89,
    view_count: 2100,
    comment_count: 34,
  },
  {
    uuid: 'mock-4',
    author_uuid: 'user-jkl-012',
    author_meta: {
      balance: 450_000,
      subscription_type: 1,
      elo_rating: 1480,
      gender: 'F',
      age: 22,
      arena: 'Toronto',
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    text: 'AI is going to replace junior analysts faster than anyone expects. Not fear-mongering — just observing the trajectory.',
    topic: 'AI and tech',
    post_type: 5,
    post_meta: { platform: 'ios' },
    upvote_count: 215,
    view_count: 8900,
    comment_count: 112,
  },
  {
    uuid: 'mock-5',
    author_uuid: 'penny',
    author_meta: {
      balance: 0,
      subscription_type: 2,
      role: 'penny',
      elo_rating: 9999,
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    title: 'NVDA earnings pick',
    text: 'Bearish into earnings. Revenue growth is decelerating and valuation is stretched.',
    topic: 'Picks',
    post_type: 7,
    post_meta: {
      platform: 'web',
      resolution_status: 'pending',
      resolution_deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
      consensus_percent: 62,
      price_history: [
        { price: 120, timestamp: Date.now() - 1000 * 60 * 60 * 24 * 5 },
        { price: 118, timestamp: Date.now() - 1000 * 60 * 60 * 24 * 4 },
        { price: 121, timestamp: Date.now() - 1000 * 60 * 60 * 24 * 3 },
        { price: 119, timestamp: Date.now() - 1000 * 60 * 60 * 24 * 2 },
        { price: 117, timestamp: Date.now() - 1000 * 60 * 60 * 24 },
      ],
    },
    upvote_count: 67,
    view_count: 1800,
    comment_count: 29,
  },
  {
    uuid: 'mock-6',
    author_uuid: 'user-pqr-678',
    author_meta: {
      balance: 1_200_000,
      subscription_type: 1,
      role: 'user',
      elo_rating: 1750,
      gender: 'M',
      age: 30,
      arena: 'Miami',
    },
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    text: 'This is exactly what I mean when I say patience is the ultimate edge in real estate. 18 months of conviction. Congrats on the close.',
    topic: 'Real estate',
    post_type: 1,
    post_meta: {
      platform: 'web',
      quote_post: {
        uuid: 'mock-2',
        author_uuid: 'user-def-456',
        author_meta: {
          balance: 850_000,
          subscription_type: 1,
          elo_rating: 1620,
          gender: 'F',
          age: 24,
          arena: 'Dubai',
        },
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        text: 'Just closed my first seven-figure real estate deal. Took 18 months from first offer to closing. The patience paid off.\n\nHappy to share the playbook if anyone\'s interested.',
        topic: 'Real estate',
        post_type: 1,
        post_meta: {
          platform: 'web',
          src: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
          media_type: 'image',
        },
        upvote_count: 127,
        view_count: 5400,
        comment_count: 56,
      },
    },
    upvote_count: 15,
    view_count: 340,
    comment_count: 3,
  },
]
