import type { Comment } from './types'

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  'mock-1': [
    {
      uuid: 'cmt-1',
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      post_uuid: 'mock-1',
      reply_parent_uuid: null,
      author_uuid: 'user-def-456',
      author_meta: {
        balance: 850_000,
        subscription_type: 1,
        elo_rating: 1620,
        gender: 'F',
        age: 24,
        arena: 'Dubai',
      },
      text: 'Agree on volatility. I\'m hedging with puts on SPY and rotating into commodities. Gold looks strong here.',
      upvote_count: 12,
      deleted_at: null,
    },
    {
      uuid: 'cmt-2',
      created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
      post_uuid: 'mock-1',
      reply_parent_uuid: 'cmt-1',
      author_uuid: 'user-abc-123',
      author_meta: {
        balance: 2_500_000,
        subscription_type: 1,
        role: 'user',
        elo_rating: 1850,
        gender: 'M',
        age: 28,
        arena: 'London',
      },
      text: 'Smart play. What strike prices are you looking at for SPY puts?',
      upvote_count: 8,
      deleted_at: null,
    },
    {
      uuid: 'cmt-3',
      created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      post_uuid: 'mock-1',
      reply_parent_uuid: 'cmt-2',
      author_uuid: 'user-def-456',
      author_meta: {
        balance: 850_000,
        subscription_type: 1,
        elo_rating: 1620,
        gender: 'F',
        age: 24,
        arena: 'Dubai',
      },
      text: 'Looking at 420P for August expiry. Premium is reasonable and gives enough time for the thesis to play out.',
      upvote_count: 5,
      deleted_at: null,
    },
    {
      uuid: 'cmt-4',
      created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      post_uuid: 'mock-1',
      reply_parent_uuid: null,
      author_uuid: 'user-ghi-789',
      author_meta: {
        balance: 12_000_000,
        subscription_type: 2,
        role: 'vip',
        elo_rating: 2100,
        gender: 'M',
        age: 35,
        arena: 'Singapore',
      },
      text: 'Earnings season will separate the wheat from the chaff. Focus on companies with real cash flows, not narratives.',
      upvote_count: 24,
      deleted_at: null,
    },
    {
      uuid: 'cmt-5',
      created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      post_uuid: 'mock-1',
      reply_parent_uuid: 'cmt-4',
      author_uuid: 'user-jkl-012',
      author_meta: {
        balance: 450_000,
        subscription_type: 1,
        elo_rating: 1480,
        gender: 'F',
        age: 22,
        arena: 'Toronto',
      },
      text: 'This. The AI hype cycle stocks are going to get crushed when they can\'t show revenue growth.',
      upvote_count: 9,
      deleted_at: null,
    },
  ],
  'mock-2': [
    {
      uuid: 'cmt-6',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      post_uuid: 'mock-2',
      reply_parent_uuid: null,
      author_uuid: 'user-ghi-789',
      author_meta: {
        balance: 12_000_000,
        subscription_type: 2,
        role: 'vip',
        elo_rating: 2100,
        gender: 'M',
        age: 35,
        arena: 'Singapore',
      },
      text: 'Congrats! What market was this in? Commercial or residential?',
      upvote_count: 15,
      deleted_at: null,
    },
    {
      uuid: 'cmt-7',
      created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      post_uuid: 'mock-2',
      reply_parent_uuid: 'cmt-6',
      author_uuid: 'user-def-456',
      author_meta: {
        balance: 850_000,
        subscription_type: 1,
        elo_rating: 1620,
        gender: 'F',
        age: 24,
        arena: 'Dubai',
      },
      text: 'Commercial — a mixed-use development in Dubai Marina. 40 units, ground floor retail.',
      upvote_count: 22,
      deleted_at: null,
    },
    {
      uuid: 'cmt-8',
      created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      post_uuid: 'mock-2',
      reply_parent_uuid: null,
      author_uuid: 'user-mno-345',
      author_meta: {
        balance: 5_500_000,
        subscription_type: 2,
        role: 'vip',
        elo_rating: 1950,
        gender: 'M',
        age: 31,
        arena: 'San Francisco',
      },
      text: 'Would love to see the playbook. DM?',
      upvote_count: 7,
      deleted_at: null,
    },
  ],
  'mock-3': [
    {
      uuid: 'cmt-9',
      created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      post_uuid: 'mock-3',
      reply_parent_uuid: null,
      author_uuid: 'user-abc-123',
      author_meta: {
        balance: 2_500_000,
        subscription_type: 1,
        role: 'user',
        elo_rating: 1850,
        gender: 'M',
        age: 28,
        arena: 'London',
      },
      text: 'Already shorting. The halving effect is priced in and macro headwinds are too strong.',
      upvote_count: 18,
      deleted_at: null,
    },
    {
      uuid: 'cmt-10',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      post_uuid: 'mock-3',
      reply_parent_uuid: 'cmt-9',
      author_uuid: 'user-jkl-012',
      author_meta: {
        balance: 450_000,
        subscription_type: 1,
        elo_rating: 1480,
        gender: 'F',
        age: 22,
        arena: 'Toronto',
      },
      text: 'Brave position. What\'s your stop loss?',
      upvote_count: 4,
      deleted_at: null,
    },
  ],
  'mock-4': [
    {
      uuid: 'cmt-11',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      post_uuid: 'mock-4',
      reply_parent_uuid: null,
      author_uuid: 'user-mno-345',
      author_meta: {
        balance: 5_500_000,
        subscription_type: 2,
        role: 'vip',
        elo_rating: 1950,
        gender: 'M',
        age: 31,
        arena: 'San Francisco',
      },
      text: 'Already happening. Our firm replaced 3 junior analyst positions with AI tooling last quarter. Saved $400k annually.',
      upvote_count: 45,
      deleted_at: null,
    },
    {
      uuid: 'cmt-deleted',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      post_uuid: 'mock-4',
      reply_parent_uuid: 'cmt-11',
      author_uuid: 'user-abc-123',
      author_meta: {
        balance: 2_500_000,
        subscription_type: 1,
        role: 'user',
        elo_rating: 1850,
        gender: 'M',
        age: 28,
        arena: 'London',
      },
      text: '',
      upvote_count: 0,
      deleted_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    },
    {
      uuid: 'cmt-12',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
      post_uuid: 'mock-4',
      reply_parent_uuid: null,
      author_uuid: 'user-def-456',
      author_meta: {
        balance: 850_000,
        subscription_type: 1,
        elo_rating: 1620,
        gender: 'F',
        age: 24,
        arena: 'Dubai',
      },
      text: 'The juniors who learn to leverage AI will be more valuable, not less. Adapt or die.',
      upvote_count: 31,
      deleted_at: null,
    },
  ],
  'mock-5': [
    {
      uuid: 'cmt-13',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
      post_uuid: 'mock-5',
      reply_parent_uuid: null,
      author_uuid: 'user-abc-123',
      author_meta: {
        balance: 2_500_000,
        subscription_type: 1,
        role: 'user',
        elo_rating: 1850,
        gender: 'M',
        age: 28,
        arena: 'London',
      },
      text: 'Interesting take. Jensen has been delivering though. What makes you think this quarter is different?',
      upvote_count: 11,
      deleted_at: null,
    },
  ],
}
